### ISSUE TITLE
Accept new tweets archive format

### ISSUE THREAD

**Issue by guilhermelimak** [hugocaillard/tweets-cleaner#3]
Would you accept a pull request adding support to the new format for the tweets archive?

Now the tweets don't come on a tweets.csv anymore, but on a tweets.js with the following format:
```js
window.YTD.tweet.part0 = [ { ...tweets content here } ]
```

I'm just not really sure if I'm missing something and the old format is still accessible but `csv` it's not mentioned anywhere on the README that comes with the archive now (I uploaded it here: https://pastebin.com/DSyZrvbp).

Just making sure this feature is wanted before starting making the PR.

**Comment by hugoclrd** [comment]
Hello @guilhermelimak, that would be more than welcome indeed 👌

**Comment by Harest** [comment]
Seems like it never happened?  
Edit : I did a quick fix for myself, not the best though as i went for the quickest. Do you want me to still do a PR for that or would like to do everything yourself @hugocaillard?  
I guess i'll just do my fork and you'll see what you do with it.  
Edit² : [Done](https://github.com/Harest/tweets-cleaner/pull/1/files). I kept my branch opened if you ever want to update the main project here. _Be sure to squash in case of a merge as i'm often too lazy on GitHub to do it properly in local to only get one commit. I wish you could do that on the site directly._

**Comment by guilhermelimak** [comment]
nope, sorry about that, ended up deleting my account and completely forgot about this
