### ISSUE TITLE
It's not working for me

### ISSUE THREAD

**Issue by migcm** [hugocaillard/tweets-cleaner#8]
Hello!

All messages appear to me as "{}" and do not delete any tweets. No error appears in the log (only "[]"). How can I check what is happening?

`{}

Next call in 500ms
`

Thanks!

**Comment by hugoclrd** [comment]
Hello @migcm 

I'm sorry I can't provide much support for this script.
I suggest that you double check the config file to make the values are correct (maxDate, regexp) and the files naming as well (mainly config.js, tweet.js).

Hope you'll figure it out 💪

**Comment by Durss** [comment]
In case that can help anyone reading this in the future, the keys need to be generated with the read-write permissions.
By default the keys only have read permissions.
See this :
[https://stackoverflow.com/questions/8389796/why-this-error-read-only-application-cannot-post](https://stackoverflow.com/questions/8389796/why-this-error-read-only-application-cannot-post)
